name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
#          cache: 'npm'
#          cache-dependency-path: package-lock.json

      - name: prepare code
        run: git clone --depth 1 https://github.com/ionic-jp/capacitor-site.git site

      # community-siteのビルド
      - name: community-site build
        run: |
          npm install
          npm run build
        working-directory: site

      # Docsのビルド
      - name: npm install, build
        run: |
          npm ci --legacy-peer-deps
          npm run build:production
          mv build site/www/docs

      # デプロイ
      - name: deploy
        run: |
          npx netlify-cli deploy \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --dir site/www/ \
            --auth ${{ secrets.NETLIFY_TOKEN }} \
            --prod
